apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ivt67ns2w-nodejs
  janus-idp.io/tekton: ivt67ns2w-nodejs
  backstage.io/kubernetes-id: ivt67ns2w-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ivt67ns2w-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
